FORMAT: 1A
HOST: https://marblejs-example.herokuapp.com/

# Marble.js IMDB-like
Example REST API written in [Marble.js](http://marblejs.com) framework. The API allows you to list all available movies and connected actors profiles. The aim of this project is not to simulate the IMDB API, but rather to demonstrate how developers can write REST APIs in Marble.js framework.

For implementation details you can visit the following link: [@marblejs/example](https://github.com/marblejs/example)

# Group API

The root endpoint should prefix all resources and right now is only accessible over HTTP.
```
https://marblejs-example.herokuapp.com
```

## Version [/api/v1]

### Get version [GET]

Retrieve information about API availability

+ Response 200 (text/plain)

        "API version: v1"

:[Auth](./auth/auth.api.apib)
:[Users](./users/users.api.apib)
:[Actors](./actors/actors.api.apib)
:[Movies](./movies/movies.api.apib)
