import { generateCollectionFromModel } from './generator';
import { Movie, MovieGenre } from '@api/movies';

const movies = [
  {
    imdbId: 'tt0816711',
    title: 'World War Z',
    director: 'David Fincher',
    year: 2013,
    metascore: 63,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.HORROR],
    actors: [{ imdbId: 'nm0000093', name: 'Brad Pitt' }],
  },
  {
    imdbId: 'tt0356910',
    title: 'Mr. & Mrs. Smith',
    director: 'Doug Liman',
    year: 2005,
    metascore: 55,
    genres: [MovieGenre.ACTION, MovieGenre.COMEDY, MovieGenre.CRIME],
    actors: [
      { imdbId: 'nm0000093', name: 'Brad Pitt' },
      { imdbId: 'nm0001401', name: 'Angelina Jolie' },
    ],
  },
  {
    imdbId: 'tt0988045',
    title: 'Sherlock Holmes',
    director: 'Guy Ritchie',
    year: 2009,
    metascore: 57,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.CRIME],
    actors: [{ imdbId: 'nm0000375', name: 'Robert Downey Jr.' }],
  },
  {
    imdbId: 'tt0371746',
    title: 'Iron Man',
    director: 'Jon Favreau',
    year: 2008,
    metascore: 79,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.SCI_FI],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
    ],
  },
  {
    imdbId: 'tt1228705',
    title: 'Iron Man 2',
    director: 'Jon Favreau',
    year: 2010,
    metascore: 57,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.SCI_FI],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
    ],
  },
  {
    imdbId: 'tt1300854',
    title: 'Iron Man 3',
    director: 'Shane Black',
    year: 2013,
    metascore: 62,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.SCI_FI],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
      { imdbId: 'nm0749263', name: 'Mark Ruffalo' },
    ],
  },
  {
    imdbId: 'tt0848228',
    title: 'Avengers',
    director: 'Joss Whedon',
    year: 2012,
    metascore: 69,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.SCI_FI],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
      { imdbId: 'nm0000168', name: 'Samuel L. Jackson' },
      { imdbId: 'nm0749263', name: 'Mark Ruffalo' },
      { imdbId: 'nm1165110', name: 'Chris Hemsworth' },
      { imdbId: 'nm1130627', name: 'Cobie Smulders' },
      { imdbId: 'nm0262635', name: 'Chris Evans' },
    ],
  },
  {
    imdbId: 'tt2395427',
    title: 'Avengers: Age of Ultron',
    director: 'Joss Whedon',
    year: 2015,
    metascore: 66,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.SCI_FI],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
      { imdbId: 'nm0000168', name: 'Samuel L. Jackson' },
      { imdbId: 'nm0749263', name: 'Mark Ruffalo' },
      { imdbId: 'nm1165110', name: 'Chris Hemsworth' },
      { imdbId: 'nm1130627', name: 'Cobie Smulders' },
      { imdbId: 'nm0262635', name: 'Chris Evans' },
    ],
  },
  {
    imdbId: 'tt4154756',
    title: 'Avengers: Infinity War',
    director: 'Anthony Russo',
    year: 2018,
    metascore: 68,
    genres: [MovieGenre.ACTION, MovieGenre.ADVENTURE, MovieGenre.FANTASY],
    actors: [
      { imdbId: 'nm0000375', name: 'Robert Downey Jr.' },
      { imdbId: 'nm0000569', name: 'Gwyneth Paltrow' },
      { imdbId: 'nm0000168', name: 'Samuel L. Jackson' },
      { imdbId: 'nm0749263', name: 'Mark Ruffalo' },
      { imdbId: 'nm1165110', name: 'Chris Hemsworth' },
      { imdbId: 'nm1130627', name: 'Cobie Smulders' },
      { imdbId: 'nm0262635', name: 'Chris Evans' },
    ],
  },
  {
    imdbId: 'tt0266697',
    title: 'Kill Bill: Vol. 1',
    director: 'Quentin Tarantino',
    year: 2003,
    metascore: 69,
    genres: [MovieGenre.ACTION, MovieGenre.CRIME, MovieGenre.THRILLER],
    actors: [{ imdbId: 'nm0000235', name: 'Uma Thurman' }],
  },
  {
    imdbId: 'tt0378194',
    title: 'Kill Bill: Vol. 2',
    director: 'Quentin Tarantino',
    year: 2004,
    metascore: 83,
    genres: [MovieGenre.ACTION, MovieGenre.CRIME, MovieGenre.THRILLER],
    actors: [{ imdbId: 'nm0000235', name: 'Uma Thurman' }],
  },
];

export const moviesGenerator = generateCollectionFromModel(Movie)(movies);
